import type { Metadata } from "next";
import {
    Noto_Sans_Georgian as font_sans,
    Noto_Serif_Georgian as font_serif,
} from "next/font/google";
import "./globals.css";

const fontSans = font_sans({
    variable: "--font-font-sans",
    subsets: ["latin"],
});

const fontSerif = font_serif({
    variable: "--font-font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fontSans.variable} ${fontSerif.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
